server:
  port: 8090
  forward-headers-strategy: framework
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_myplans_auth?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: flase
      path: /h2-console

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000